controller:

  # image: "jenkins/jenkins"
  # tag: "latest"
  # tagLabel: jdk11
  imagePullPolicy: "IfNotPresent"

  adminUsername: admin
  adminPassword: admin1234

  additionalPlugins:
    - job-dsl:1.7
    - permissive-script-security:0.7
    - github:1.37.0
    - docker-plugin:latest
    - docker-workflow:latest

  javaOpts: '-Dpermissive-script-security.enabled=true'

  # runAsUser: 0
  # fsGroup: 0

  # podSecurityContextOverride:
  #   runAsUser: 0
  #   runAsNonRoot: false
  #   supplementalGroups: [0]

  # containerSecurityContext:
  #   runAsUser: 0
  #   runAsGroup: 0
  #   readOnlyRootFilesystem: false
  #   allowPrivilegeEscalation: true

  JCasC:
    defaultConfig: true

  # LOCAL ONLY:
  serviceType: NodePort
serviceAccount:
  create: false
  name: jenkins
  annotations: {}